[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
arbor_program = "4BS3mc2pR7WGrS1QDTraDzvtuEriHor114Epc2LJSFcC"

[programs.localnet]
arbor_program = "4BS3mc2pR7WGrS1QDTraDzvtuEriHor114Epc2LJSFcC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
