[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
arbor_program = "82kzsHhGThuVdNvUm6eCchTL9CYTp6s7bufFZ3ARBtYH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
