[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
arbor_program = "AAJosF3mpieT9UwnTv7B9B1mR7TVm37xSKPP87kppKoL"

[programs.localnet]
arbor_program = "AAJosF3mpieT9UwnTv7B9B1mR7TVm37xSKPP87kppKoL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
